In [1]:

from keras import backend as K
import tensorflow as tf
import pandas as pd 
import numpy as np
import math
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import collections
import progressbar
import time
from time import process_time
import sys
import os
import random
import gc
    
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from imblearn.under_sampling import RandomUnderSampler 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import f1_score,classification_report,roc_auc_score,precision_score,recall_score, precision_recall_fscore_support 
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.layers import Dropout


#from sklearn_som.som import SOM
import networkx as nx
from networkx.algorithms import approximation

pd.set_option('display.max_columns', 100)


print("import terminé a :",time.strftime("%H:%M:%S", time.localtime()))


import terminé a : 17:21:28


In [25]:
class markov_chain:
    
    # args=une liste d'argument classique
    # kwargs : max_iter=1000---> {'max_iter':'1000'}
    def __init__(self, *args, **kwargs):
        if(len(args)==0):
            self.graph =nx.Graph()
            curent_node_name="start"
        if(len(args)==1):
            self.graph = args[0]
            curent_node_name="start"
        if(len(args)==2):
            self.graph = args[0]
            curent_node_name=args[1]
            
            
    def set_g(self, graph): 
        self.graph = graph       
    def get_g(self):
        return self.graph
    def set_curent_node_name(self, name): 
        self.curent_node_name = name       
    def get_curent_node_name(self):
        return self.curent_node_name
    def find_stationary_distribution(self):
        return type(self.graph)

In [26]:
g=nx.MultiGraph()
curent_node_name="start"
cm=markov_chain(g)
print(cm.get_g())

MultiGraph with 0 nodes and 0 edges


In [7]:
import numpy as np
from sklearn import preprocessing
transition_mat = np.matrix([
    [.95, .05, 0., 0.],\
    [0., 0.9, 0.09, 0.01],\
    [0., 0.05, 0.9, 0.05],\
    [0.8, 0., 0.05, 0.15]])

In [20]:
def is_stochastic(transition_mat):
    i=0
    maxi=len(transition_mat)
    while(i<maxi):
        s=sum(transition_mat[i])
        
        if(s>1.00001):
            return False
        if(s<0.99999):
            return False
        i+=1
    return True

def power_method(transition_mat):
    in_progress=transition_mat
    for i in range(100):
        in_progress=np.matmul(in_progress,transition_mat)
        sum_of_rows = in_progress.sum(axis=1)
        #print(in_progress.shape)
        in_progress = preprocessing.normalize(in_progress, norm="l1")

    return in_progress[0]

In [24]:
expeced_distribution=[ 0.34782609  ,0.32608696,  0.30434783 , 0.02173913]
print(in_progress)
#print(is_stochastic(expeced_distribution))

[[0.34784417 0.32608818 0.30432971 0.02173793]
 [0.34780696 0.32608571 0.30436694 0.02174039]
 [0.34782453 0.3260868  0.30434943 0.02173924]
 [0.34784535 0.32608825 0.30432854 0.02173786]]


In [25]:
print(in_progress[0])

[0.34784417 0.32608818 0.30432971 0.02173793]


In [26]:
print(is_stochastic(in_progress))

True


In [31]:
big_mat=[[-5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1/2, -6, 5, 0, 0, 1/2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, -7, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, -7, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, -2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1/5, 0, 0, 0, 0, -26/5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1/5, 0, 0, 0, 1/2, -31/5, 5, 0, 0, 1/2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1/5, 0, 0, 0, 1, -36/5, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1/5, 0, 0, 0, 1, -36/5, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1/5, 0, 0, 0, 1, -11/5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 2/5, 0, 0, 0, 0, -27/5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 2/5, 0, 0, 0, 1/2, -32/5, 5, 0, 0, 1/2, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 2/5, 0, 0, 0, 1, -37/5, 5, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 2/5, 0, 0, 0, 1, -37/5, 5, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 2/5, 0, 0, 0, 1, -12/5, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2/5, 0, 0, 0, 0, -27/5, 5, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2/5, 0, 0, 0, 1/2, -32/5, 5, 0, 1/2, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2/5, 0, 0, 0, 1/2, -32/5, 5, 0, 1/2, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2/5, 0, 0, 0, 1/2, -7/5, 0, 0, 1/2],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2/5, 0, 0, 0, -27/5, 5, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2/5, 0, 0, 0, -27/5, 5],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2/5, 0, 0, 0, -2/5]]

val=power_method(big_mat)

print("big_mat is stochastic ",is_stochastic(big_mat))
print(val)
print(sum(val))

big_mat is stochastic  False
[ 8.85391380e-05 -1.00500335e-03  4.03557942e-03 -8.13188176e-03
  5.05782750e-03  1.13520672e-03 -1.15480978e-02  4.16532690e-02
 -7.62635571e-02  4.54829191e-02 -8.79825393e-04  1.79054661e-02
 -9.39229698e-02  2.21202190e-01 -1.45933933e-01 -7.35801740e-03
  5.23947050e-02 -1.35823193e-01  9.23800579e-02 -5.37305672e-03
  1.86642398e-02 -1.37604644e-02]
-2.7755575615628914e-17


In [33]:
import time
start = time.time()

--- graph dist = 0.0 seconds ---
--- graph dist = 0.0 seconds ---


In [34]:
print("--- temps hors ligne = %s seconds ---" % (time.time() - start));start = time.time()
#his

--- temps hors ligne = 4059.499307155609 seconds ---


In [35]:
print("--- temps hors ligne = %s seconds ---" % (time.time() - start));start = time.time()
#mine

--- temps hors ligne = 523.7105548381805 seconds ---


In [55]:
start = time.time()
#his

In [56]:
print("--- temps hors ligne = %s seconds ---" % (time.time() - start))

--- temps hors ligne = 1100.375866651535 seconds ---


In [39]:
if ( False & True):
    print("tt")

In [50]:
d1={'MMMMMMMMMMMMM':1,'0': {'precision': 0.9989910293666407, 'recall': 0.9998139363481666, 'f1-score': 0.9994023134622121, 'support': 553574},
    '1': {'precision': 0.9390171699230314, 'recall': 0.7393939393939394, 'f1-score': 0.8273343766301513, 'support': 2145},
    'accuracy': 0.998808750465613, 
    'macro avg':{'precision': 0.9690040996448361, 'recall': 0.869603937871053, 'f1-score': 0.9133683450461817, 'support': 555719}, 
    'weighted avg': {'precision': 0.9987595383999713, 'recall': 0.998808750465613, 'f1-score': 0.9987381545536542, 'support': 555719}}

d2={'MMMMMMMMMMMMM':2,'0': {'precision': 0.9990091021815997, 'recall': 0.9998554845422654, 'f1-score': 0.9994321141694287, 'support': 553574}, '1': {'precision': 0.9522673031026253, 'recall': 0.7440559440559441, 'f1-score': 0.8353834074849517, 'support': 2145}, 'accuracy': 0.9988681329952728, 'macro avg': {'precision': 0.9756382026421124, 'recall': 0.8719557142991048, 'f1-score': 0.9174077608271902, 'support': 555719}, 'weighted avg': {'precision': 0.9988286851740394, 'recall': 0.9988681329952728, 'f1-score': 0.9987989084020567, 'support': 555719}}

d3={'MMMMMMMMMMMMM':3,'0': {'precision': 0.9991296606940685, 'recall': 0.9995501956378009, 'f1-score': 0.9993398839243223, 'support': 553574}, '1': {'precision': 0.8697698744769874, 'recall': 0.7752913752913753, 'f1-score': 0.8198175992112399, 'support': 2145}, 'accuracy': 0.9986845869945062, 'macro avg': {'precision': 0.9344497675855279, 'recall': 0.8874207854645881, 'f1-score': 0.9095787415677811, 'support': 555719}, 'weighted avg': {'precision': 0.9986303494568505, 'recall': 0.9986845869945062, 'f1-score': 0.9986469522435456, 'support': 555719}}


In [51]:
print(d1["1"]['f1-score'])

0.8273343766301513


In [52]:
list_test=list()
list_test.append(d1)
list_test.append(d2)
list_test.append(d3)

In [53]:
for d in list_test:
    print(d["1"]['f1-score'])

0.8273343766301513
0.8353834074849517
0.8198175992112399


In [54]:
return_value=sorted(list_test, key=lambda d: d["1"]['f1-score'],reverse=True)
print(return_value)

[{'MMMMMMMMMMMMM': 2, '0': {'precision': 0.9990091021815997, 'recall': 0.9998554845422654, 'f1-score': 0.9994321141694287, 'support': 553574}, '1': {'precision': 0.9522673031026253, 'recall': 0.7440559440559441, 'f1-score': 0.8353834074849517, 'support': 2145}, 'accuracy': 0.9988681329952728, 'macro avg': {'precision': 0.9756382026421124, 'recall': 0.8719557142991048, 'f1-score': 0.9174077608271902, 'support': 555719}, 'weighted avg': {'precision': 0.9988286851740394, 'recall': 0.9988681329952728, 'f1-score': 0.9987989084020567, 'support': 555719}}, {'MMMMMMMMMMMMM': 1, '0': {'precision': 0.9989910293666407, 'recall': 0.9998139363481666, 'f1-score': 0.9994023134622121, 'support': 553574}, '1': {'precision': 0.9390171699230314, 'recall': 0.7393939393939394, 'f1-score': 0.8273343766301513, 'support': 2145}, 'accuracy': 0.998808750465613, 'macro avg': {'precision': 0.9690040996448361, 'recall': 0.869603937871053, 'f1-score': 0.9133683450461817, 'support': 555719}, 'weighted avg': {'precis

In [59]:
i=0
while(True&(i<10)):
    (print(i))
    i+=1

0
1
2
3
4
5
6
7
8
9
